receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  transform/falco_to_sigma:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - 'set(attributes["Image"], attributes["proc.name"])'
          - 'set(attributes["TargetFilename"], attributes["fd.name"]) where attributes["fd.name"] != nil'
          - 'set(attributes["TargetFilename"], attributes["evt.arg.filename"]) where attributes["evt.arg.filename"] != nil'
          - 'set(attributes["proc.name"], "wget") where attributes["proc.name"] == nil and IsMatch(attributes["proc.cmdline"], "^wget\\s")'

  batch:

exporters:
  otlp/sigma:
    endpoint: "localhost:55680"
    tls:
      insecure: true
  file/falco_jsonl:           
    path: ./falco_agent/event/events.jsonl
    rotation:
      max_megabytes: 100
      max_backups:   5
    format: json
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [transform/falco_to_sigma, batch]
      exporters:  [otlp/sigma, file/falco_jsonl, debug] 

  telemetry:
    logs:
      level: debug

